apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-recipe-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-recipe-web
  template:
    metadata:
      labels:
        app: react-recipe-web
    spec:
      containers:
      - name: react-recipe-web
        image: ychandrakumaran/react-recipe_web
        ports:
        - containerPort: 3000

apiVersion: v1
kind: Service
metadata:
  name: react-recipe-web
spec:
  type: NodePort
  selector:
    app: react-recipe-web
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
